;;; -*- Mode: Lisp -*-

(defpackage :foundationdb
  (:use #:common-lisp #:cffi)
  (:export 
   #:*foreign-encoding*
   #:api-version
   #:cluster-destroy
   #:cluster-open-database
   #:cluster-set-option
   #:counter-add
   #:counter-clear
   #:counter-get-snapshot
   #:counter-get-transactional
   #:counter-set
   #:database
   #:database-close
   #:database-create-transaction
   #:database-destroy
   #:database-open
   #:database-set-option
   #:directory-subspace
   #:directory-subspace-delete
   #:directory-subspace-exists-p
   #:directory-subspace-list
   #:directory-subspace-open
   #:directory-subspace-path
   #:directory-subspace-rename
   #:do-range-query
   #:fdb-error
   #:future-block-until-ready
   #:future-callback
   #:future-cancel
   #:future-destroy
   #:future-ready-p
   #:future-value
   #:key-octets
   #:key-selector
   #:key-selector-add
   #:key-selector-first-greater-or-equal
   #:key-selector-first-greater-than
   #:key-selector-last-less-or-equal
   #:key-selector-last-less-than
   #:key-successor
   #:make-cluster
   #:make-counter
   #:make-range
   #:make-range-query
   #:make-root-directory
   #:make-subspace
   #:make-tuple
   #:map-range-query
   #:network-set-option
   #:network-start
   #:network-stop
   #:range-starts-with
   #:root-directory
   #:subspace
   #:subspace-contains-key-p
   #:subspace-decode-key
   #:subspace-encode-key
   #:subspace-range
   #:transaction
   #:transaction-add-conflict-range
   #:transaction-addresses-for-key
   #:transaction-cancel
   #:transaction-clear
   #:transaction-commit
   #:transaction-commit-or-retry
   #:transaction-committed-version
   #:transaction-destroy
   #:transaction-get
   #:transaction-key
   #:transaction-range
   #:transaction-range-query
   #:transaction-range-query-next
   #:transaction-read-version
   #:transaction-reset
   #:transaction-set
   #:transaction-set-option
   #:transaction-snapshot
   #:transaction-watch
   #:tuple-octets
   #:tuple-decode
   #:tuple-elt
   #:tuple-encode
   #:tuple-encode-item
   #:tuple-encoded-length
   #:tuple-equalp
   #:tuple-greaterp
   #:tuple-length
   #:tuple-lessp
   #:tuple-not-equalp
   #:tuple-not-greaterp
   #:tuple-not-lessp
   #:tuple-push
   #:tuple-range
   #:tuple-subtuple
   #:value-octets
   #:with-transaction
))
